In [4]:
import pandas as pd
import matplotlib as plt
import numpy as np

df = pd.read_csv('2016_Building_Energy_Benchmarking.csv', sep=",")

In [5]:
df

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3.946027e+06,12764.529300,1.276453e+06,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3.242851e+06,51450.816410,5.145082e+06,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,4.952666e+07,14938.000000,1.493800e+06,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,8.115253e+05,2.768924e+06,18112.130860,1.811213e+06,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,1.573449e+06,5.368607e+06,88039.984380,8.803998e+06,False,NaN,Compliant,NaN,505.01,2.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3371,50222,2016,Nonresidential COS,Office,Horticulture building,1600 S Dakota St,Seattle,WA,NaN,1624049080,...,1.536550e+05,5.242709e+05,3254.750244,3.254750e+05,True,NaN,Error - Correct Default Data,NaN,20.94,1.70
3372,50223,2016,Nonresidential COS,Other,International district/Chinatown CC,719 8th Ave S,Seattle,WA,NaN,3558300000,...,1.162210e+05,3.965461e+05,5537.299805,5.537300e+05,False,NaN,Compliant,NaN,32.17,2.01
3373,50224,2016,Nonresidential COS,Other,Queen Anne Pool,1920 1st Ave W,Seattle,WA,NaN,1794501150,...,5.252517e+05,1.792159e+06,39737.390630,3.973739e+06,False,NaN,Compliant,NaN,223.54,16.99
3374,50225,2016,Nonresidential COS,Mixed Use Property,South Park Community Center,8319 8th Ave S,Seattle,WA,NaN,7883603155,...,1.022480e+05,3.488702e+05,3706.010010,3.706010e+05,False,NaN,Compliant,NaN,22.11,1.57
3375,50226,2016,Nonresidential COS,Mixed Use Property,Van Asselt Community Center,2820 S Myrtle St,Seattle,WA,NaN,7857002030,...,1.267744e+05,4.325542e+05,7203.419922,7.203420e+05,False,NaN,Compliant,NaN,41.27,2.26

In [6]:
df['DataYear'].unique()

array([2016])

In [13]:
df['BuildingType'].unique()

array(['NonResidential', 'Nonresidential COS', 'Multifamily MR (5-9)',
       'SPS-District K-12', 'Campus', 'Multifamily LR (1-4)',
       'Multifamily HR (10+)', 'Nonresidential WA'], dtype=object)

In [8]:
df[df['PrimaryPropertyType'] == 'Mid-Rise Multifamily']

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
9,13,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Lyon Building,607 - 3rd Ave.,Seattle,WA,98104.0,0939000105,...,7.420912e+05,2532015.0,10020.259770,1002026.0,False,NaN,Compliant,NaN,151.12,2.37
165,265,2016,Multifamily MR (5-9),Mid-Rise Multifamily,YWCA Opportunity Place,2024 3rd Avenue,Seattle,WA,98121.0,8729690000,...,1.612728e+06,5502627.0,45374.941410,4537494.0,False,NaN,Compliant,NaN,279.35,2.39
173,280,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Wintonia,1431 Minor Ave,Seattle,WA,98101.0,8725600350,...,4.903724e+05,1673151.0,25164.187500,2516419.0,False,NaN,Compliant,NaN,145.31,2.80
189,297,2016,Multifamily MR (5-9),Mid-Rise Multifamily,LAKE CITY COURT,12730 33RD AVE NE,Seattle,WA,98125.0,3993000000,...,4.558248e+05,1555274.0,9186.879883,918688.0,False,NaN,Compliant,NaN,59.63,1.05
486,655,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Tashiro_kaplan,101 Prefontaine PL S,Seattle,WA,98104.0,8566600000,...,9.148228e+05,3121375.0,665.750000,66575.0,False,NaN,Compliant,NaN,25.30,0.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3345,50076,2016,Multifamily MR (5-9),Mid-Rise Multifamily,bridges@11th,4557 11th Ave NE,Seattle,WA,98105.0,6746701320,...,9.477269e+05,3233644.0,11994.469730,1199447.0,False,NaN,Compliant,NaN,86.25,0.37
3349,50084,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Rooster Apartments,900 NE 65th St,Seattle,WA,98115.0,9528103070,...,9.084525e+05,3099640.0,34628.171880,3462817.0,False,NaN,Compliant,NaN,205.52,0.96
3353,50090,2016,Multifamily MR (5-9),Mid-Rise Multifamily,131910 - LIV Seattle,4717 Brooklyn Ave NE,Seattle,WA,98105.0,8817400110,...,4.407752e+05,1503925.0,8337.259766,833726.0,False,NaN,Compliant,NaN,54.76,0.86
3355,50093,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Raven Terrace,820 Yesler Way,Seattle,WA,98104.0,9822000080,...,6.334232e+05,2161240.0,0.000000,0.0,False,NaN,Compliant,NaN,15.07,0.18
3357,50095,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Broadstone Sky,4745 40th Ave SW,Seattle,WA,98116.0,7579200395,...,5.828756e+05,1988772.0,15634.129880,1563413.0,False,NaN,Compliant,NaN,96.90,0.47

In [9]:
df['YearBuilt'].unique()

array([1927, 1996, 1969, 1926, 1980, 1999, 1904, 1910, 1998, 1928, 1922,
       2004, 1930, 1983, 1907, 1916, 1985, 1961, 2001, 1991, 1955, 1978,
       1949, 1989, 1906, 1994, 1992, 1990, 1950, 1900, 1954, 1911, 1973,
       1920, 1982, 1908, 1959, 2000, 1997, 1962, 1970, 2008, 1948, 1965,
       1929, 2010, 1938, 1986, 2002, 1923, 2003, 1957, 1964, 1941, 1963,
       2006, 1915, 1958, 2009, 2011, 1971, 2007, 1951, 1953, 1952, 1960,
       1937, 1966, 1968, 1925, 1924, 2005, 1909, 1931, 1972, 1914, 1913,
       1917, 1995, 1981, 1976, 1988, 1979, 1947, 1984, 1956, 1912, 1977,
       1921, 1945, 1974, 1975, 1946, 1967, 1987, 1940, 1932, 1993, 1918,
       1905, 1902, 1939, 1944, 1942, 1903, 2012, 2013, 2015, 1901, 1919,
       2014, 1936, 1935])

In [12]:
for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

OSEBuildingID - 0%
DataYear - 0%
BuildingType - 0%
PrimaryPropertyType - 0%
PropertyName - 0%
Address - 0%
City - 0%
State - 0%
ZipCode - 0%
TaxParcelIdentificationNumber - 0%
CouncilDistrictCode - 0%
Neighborhood - 0%
Latitude - 0%
Longitude - 0%
YearBuilt - 0%
NumberofBuildings - 0%
NumberofFloors - 0%
PropertyGFATotal - 0%
PropertyGFAParking - 0%
PropertyGFABuilding(s) - 0%
ListOfAllPropertyUseTypes - 0%
LargestPropertyUseType - 1%
LargestPropertyUseTypeGFA - 1%
SecondLargestPropertyUseType - 50%
SecondLargestPropertyUseTypeGFA - 50%
ThirdLargestPropertyUseType - 82%
ThirdLargestPropertyUseTypeGFA - 82%
YearsENERGYSTARCertified - 96%
ENERGYSTARScore - 25%
SiteEUI(kBtu/sf) - 0%
SiteEUIWN(kBtu/sf) - 0%
SourceEUI(kBtu/sf) - 0%
SourceEUIWN(kBtu/sf) - 0%
SiteEnergyUse(kBtu) - 0%
SiteEnergyUseWN(kBtu) - 0%
SteamUse(kBtu) - 0%
Electricity(kWh) - 0%
Electricity(kBtu) - 0%
NaturalGas(therms) - 0%
NaturalGas(kBtu) - 0%
DefaultData - 0%
Comments - 100%
ComplianceStatus - 0%
Outlier - 99%
TotalGHGEmissions - 0%
GHGEmissionsIntensity - 0%

In [ ]:
data = df['PropertyGFATotal','NumberofFloors',]
# feature engineering / ajout de geature a partir des features existentes
#